from __future__ import annotations

from pathlib import Path

import pandas as pd


def export_report(result: dict, output_dir: str | Path = 'reports', name: str = 'backtest_report') -> dict[str, Path]:
    """Export CSV files and a lightweight HTML summary."""
    output = Path(output_dir)
    output.mkdir(parents=True, exist_ok=True)
    history = result['history']
    trades = result['trades']
    metrics = pd.Series(result['metrics'], name='Value')

    paths = {
        'history': output / f'{name}_equity_curve.csv',
        'trades': output / f'{name}_trade_log.csv',
        'metrics': output / f'{name}_metrics.csv',
        'html': output / f'{name}.html',
    }
    history.to_csv(paths['history'])
    trades.to_csv(paths['trades'], index=False)
    metrics.to_csv(paths['metrics'])

    metric_table = metrics.to_frame().to_html(float_format=lambda x: f'{x:,.4f}')
    trade_preview = trades.tail(25).to_html(index=False) if not trades.empty else '<p>No trades generated.</p>'
    html = f"""
    <html><head><title>Backtest Report</title>
    <style>body{{font-family:Arial,sans-serif;margin:32px;max-width:1100px}} table{{border-collapse:collapse;width:100%;margin:16px 0}} td,th{{border:1px solid #ddd;padding:8px}} th{{background:#f3f3f3}}</style>
    </head><body>
    <h1>{result.get('strategy', 'Strategy')} Backtest Report</h1>
    <h2>Metrics</h2>{metric_table}
    <h2>Recent Trades</h2>{trade_preview}
    <p>Generated by the Algorithmic Trading Backtester.</p>
    </body></html>
    """
    paths['html'].write_text(html, encoding='utf-8')
    return paths
